/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { Creator, CreatorDetails } from "../models";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { ButtonProps, DividerProps, FlexProps, IconProps, TextFieldProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type EditProfilePopupOverridesProps = {
    EditProfilePopup?: PrimitiveOverrideProps<FlexProps>;
    EditProfileFrame?: PrimitiveOverrideProps<ViewProps>;
    Content?: PrimitiveOverrideProps<FlexProps>;
    "Edit Profile38042978"?: PrimitiveOverrideProps<FlexProps>;
    Icon?: PrimitiveOverrideProps<ViewProps>;
    Vector?: PrimitiveOverrideProps<IconProps>;
    "Edit Profile38042981"?: PrimitiveOverrideProps<TextProps>;
    Divider38042982?: PrimitiveOverrideProps<DividerProps>;
    Form?: PrimitiveOverrideProps<FlexProps>;
    FirstNameInput?: PrimitiveOverrideProps<TextFieldProps>;
    LastNameInput?: PrimitiveOverrideProps<TextFieldProps>;
    CoverPhoto?: PrimitiveOverrideProps<FlexProps>;
    label38043079?: PrimitiveOverrideProps<TextProps>;
    Input38043080?: PrimitiveOverrideProps<FlexProps>;
    IdentityInput?: PrimitiveOverrideProps<FlexProps>;
    label38043016?: PrimitiveOverrideProps<TextProps>;
    IdentityInput1?: PrimitiveOverrideProps<TextFieldProps>;
    IdentityInput2?: PrimitiveOverrideProps<TextFieldProps>;
    IdentityInput3?: PrimitiveOverrideProps<TextFieldProps>;
    IdentityInput4?: PrimitiveOverrideProps<TextFieldProps>;
    IdentityInput5?: PrimitiveOverrideProps<TextFieldProps>;
    "Meet FirstName"?: PrimitiveOverrideProps<FlexProps>;
    ProfilePhoto?: PrimitiveOverrideProps<FlexProps>;
    label38043063?: PrimitiveOverrideProps<TextProps>;
    Input38043075?: PrimitiveOverrideProps<FlexProps>;
    CreatorDescriptionInput?: PrimitiveOverrideProps<TextFieldProps>;
    SocialMediaInputs?: PrimitiveOverrideProps<FlexProps>;
    YoutubeInput?: PrimitiveOverrideProps<FlexProps>;
    "Username Label38043138"?: PrimitiveOverrideProps<FlexProps>;
    label38043096?: PrimitiveOverrideProps<TextProps>;
    Input38043126?: PrimitiveOverrideProps<FlexProps>;
    youtubeIDInput?: PrimitiveOverrideProps<TextFieldProps>;
    "Video Embed Links"?: PrimitiveOverrideProps<FlexProps>;
    "Embed Link 138043121"?: PrimitiveOverrideProps<FlexProps>;
    label38043122?: PrimitiveOverrideProps<TextProps>;
    EmbedLink38344061?: PrimitiveOverrideProps<TextFieldProps>;
    "Embed Link 238344124"?: PrimitiveOverrideProps<FlexProps>;
    label38344125?: PrimitiveOverrideProps<TextProps>;
    EmbedLink38344126?: PrimitiveOverrideProps<TextFieldProps>;
    "Embed Link 338344273"?: PrimitiveOverrideProps<FlexProps>;
    label38344274?: PrimitiveOverrideProps<TextProps>;
    EmbedLink38344275?: PrimitiveOverrideProps<TextFieldProps>;
    LinkedinInput?: PrimitiveOverrideProps<FlexProps>;
    "Username Label38043140"?: PrimitiveOverrideProps<FlexProps>;
    label38043141?: PrimitiveOverrideProps<TextProps>;
    Input38043142?: PrimitiveOverrideProps<FlexProps>;
    linkedinIDInput?: PrimitiveOverrideProps<TextFieldProps>;
    "Linkedin Post Embed Links"?: PrimitiveOverrideProps<FlexProps>;
    "Embed Link 138344346"?: PrimitiveOverrideProps<FlexProps>;
    label38344347?: PrimitiveOverrideProps<TextProps>;
    LinkedinPostEmbedLink1?: PrimitiveOverrideProps<TextFieldProps>;
    "Embed Link 238344349"?: PrimitiveOverrideProps<FlexProps>;
    label38344350?: PrimitiveOverrideProps<TextProps>;
    LinkedinPostEmbedLink2?: PrimitiveOverrideProps<TextFieldProps>;
    "Embed Link 338344352"?: PrimitiveOverrideProps<FlexProps>;
    label38344353?: PrimitiveOverrideProps<TextProps>;
    LinkedinPostEmbedLink3?: PrimitiveOverrideProps<TextFieldProps>;
    TwitterInput?: PrimitiveOverrideProps<FlexProps>;
    "Username Label38043163"?: PrimitiveOverrideProps<FlexProps>;
    label38043164?: PrimitiveOverrideProps<TextProps>;
    Input38043165?: PrimitiveOverrideProps<FlexProps>;
    twitterIDInput?: PrimitiveOverrideProps<TextFieldProps>;
    "Tweet Embed Links"?: PrimitiveOverrideProps<FlexProps>;
    "Embed Link 138344641"?: PrimitiveOverrideProps<FlexProps>;
    label38344642?: PrimitiveOverrideProps<TextProps>;
    TweetEmbedLink1?: PrimitiveOverrideProps<TextFieldProps>;
    "Embed Link 238344644"?: PrimitiveOverrideProps<FlexProps>;
    label38344645?: PrimitiveOverrideProps<TextProps>;
    TweetEmbedLink2?: PrimitiveOverrideProps<TextFieldProps>;
    "Embed Link 338344647"?: PrimitiveOverrideProps<FlexProps>;
    label38344648?: PrimitiveOverrideProps<TextProps>;
    TweetEmbedLink3?: PrimitiveOverrideProps<TextFieldProps>;
    FacebookInput?: PrimitiveOverrideProps<FlexProps>;
    "Username Label38043186"?: PrimitiveOverrideProps<FlexProps>;
    label38043187?: PrimitiveOverrideProps<TextProps>;
    Input38043188?: PrimitiveOverrideProps<FlexProps>;
    facebookIDInput?: PrimitiveOverrideProps<TextFieldProps>;
    "Facebook Post Embed Links"?: PrimitiveOverrideProps<FlexProps>;
    "Embed Link 138344851"?: PrimitiveOverrideProps<FlexProps>;
    label38344852?: PrimitiveOverrideProps<TextProps>;
    FacebookPostEmbedLink1?: PrimitiveOverrideProps<TextFieldProps>;
    "Embed Link 238344854"?: PrimitiveOverrideProps<FlexProps>;
    label38344855?: PrimitiveOverrideProps<TextProps>;
    FacebookPostEmbedLink2?: PrimitiveOverrideProps<TextFieldProps>;
    "Embed Link 338344857"?: PrimitiveOverrideProps<FlexProps>;
    label38344858?: PrimitiveOverrideProps<TextProps>;
    FacebookPostEmbedLink3?: PrimitiveOverrideProps<TextFieldProps>;
    Divider38042990?: PrimitiveOverrideProps<DividerProps>;
    "Frame 324"?: PrimitiveOverrideProps<FlexProps>;
    Button?: PrimitiveOverrideProps<ButtonProps>;
} & EscapeHatchProps;
export declare type EditProfilePopupProps = React.PropsWithChildren<Partial<FlexProps> & {
    creator?: Creator;
    creatorDetails?: CreatorDetails;
} & {
    overrides?: EditProfilePopupOverridesProps | undefined | null;
}>;
export default function EditProfilePopup(props: EditProfilePopupProps): React.ReactElement;
