/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-west-1",
  aws_appsync_graphqlEndpoint:
    "https://fyuvkketdbelbfsillyggrytta.appsync-api.us-west-1.amazonaws.com/graphql",
  aws_appsync_region: "us-west-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-7leh7o7f3vhyba5zz7lw44onaq",
  aws_cognito_identity_pool_id:
    "us-west-1:9cbe8eb0-4b43-4958-9e2c-90cfd5410c6c",
  aws_cognito_region: "us-west-1",
  aws_user_pools_id: "us-west-1_MZBSk9xVN",
  aws_user_pools_web_client_id: "fd5lt4v9a7dj31dsvbgt3gs0n",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["PREFERRED_USERNAME"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      "REQUIRES_LOWERCASE",
      "REQUIRES_NUMBERS",
      "REQUIRES_UPPERCASE",
    ],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
